add maximum expiration logic
matze/wastebin pull request #55
Opened 2024-06-03 18:48 UTC by bt-nia

Disclaimer: I never programmed RUST and this is purely AI generated code

This aims to implement https://github.com/matze/wastebin/issues/54

2024-06-21 15:15 UTC, bt-nia commented
any update on this? :)

2024-06-24 22:03 UTC, matze commented
I left a change request a while ago, regarding the `max_expiration()` function.

2024-06-25 07:54 UTC, bt-nia commented
@matze can you please point me to it? I can't find it.

2024-06-27 21:12 UTC, matze commented
Wait, you can't see the "Please return Option<i64> and Ok(None) here." referring to line 89 in` env.rs`?

2024-06-28 09:52 UTC, bt-nia commented
Not sure where I can see that? This is my change view: 
<img width="1183" alt="image" src="https://github.com/matze/wastebin/assets/74181389/f7fda81b-6446-438b-bc0a-ccb76ff18b43">
I've never submitted change requests in Github, but I can say that in Gitlab it is easy to accidentally only submit comments for review but never actually _post_ the review.

2024-07-01 19:58 UTC, matze requested changes

2024-07-01 19:58 UTC, matze commented on src/env.rs
> +            |_| Ok(-1), // Default to -1 if not set
Please return `Option<i64>` and `Ok(None)` here.

2024-07-01 19:59 UTC, matze commented
Sorry, you couldn't see it until I submitted the review :see_no_evil:

2024-07-02 11:51 UTC, bt-nia commented on src/env.rs
> +            |_| Ok(-1), // Default to -1 if not set
I looked into this and from a typing perspective this is counter-intuitive: This function is supposed to return an integer and None is not an integer. 
Given that Rust is a typed language, I would argue it is better to return a predictable type here instead.

2024-07-02 11:54 UTC, bt-nia commented
I was able to test the code now and made some improvements to the index.html template. 
I looked into your proposal, but from what it seems to me it is mostly a complication that makes value types less predictable. 

Unless you see any glaring issues, in which case: please let me know, could we please merge this? It is a feature we would really like to use :)

2024-07-04 20:47 UTC, matze requested changes

2024-07-04 20:47 UTC, matze commented on src/env.rs
> +            |_| Ok(-1), // Default to -1 if not set
> Given that Rust is a typed language, I would argue it is better to return a predictable type here instead.

But `Option<i64>` is a proper type and `None` reflects the absence of a value better than `-1`.

2024-07-05 11:07 UTC, bt-nia commented on src/env.rs
> +            |_| Ok(-1), // Default to -1 if not set
I adjusted the code.

2024-07-10 14:11 UTC, closed without merging