Make use of NonZero
matze/wastebin pull request #68
Opened 2024-09-22 10:11 UTC by cgzones

Make clear to readers that the value 0 is not supported and has no special meaning.

Also allows the compiler to improve enum layouts.

2024-09-23 08:06 UTC, matze commented
Please add a `CHANGELOG.md` entry and mark it as a breaking change.

2024-09-23 08:07 UTC, matze requested changes
Please add a `CHANGELOG.md` entry and mark it as a breaking change.

2024-09-25 17:20 UTC, cgzones commented
> Please add a `CHANGELOG.md` entry and mark it as a breaking change.

Added a Changelog entry, restored the possibility to explicitly specify `WASTEBIN_MAX_PASTE_EXPIRATION=0` and thus not marked it breaking.

2024-09-30 19:25 UTC, matze approved these changes

2024-09-30 19:29 UTC, merged

2024-09-30 19:29 UTC, matze commented
Thanks for this as well :+1: