Security headers
matze/wastebin pull request #80
Opened 2024-11-12 17:52 UTC by cgzones

Modern browser support security headers, in particular Content Security
Policy (CSP)(https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP).
These can help mitigating XSS vulnerabilities, in the case of pastes by
disallowing inline styles and scripts.

Move all current inline styles into the global style.css, and refactor
all inline javascript into separate asset files.

2024-12-23 20:22 UTC, matze requested changes

2024-12-23 20:22 UTC, matze commented on src/main.rs
> +async fn securityheaders_layer(
Tiniest nit:
```suggestion
async fn security_headers_layer(
```

2024-12-23 20:23 UTC, matze commented
Could you either rename the PR title or split it into multiple PRs? Some commits are not necessarily related to security headers.

2025-01-07 18:44 UTC, cgzones commented
The refactoring in the first commit is necessary to avoid the `unsafe-inline` exemption for scripts, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_inline_script

2025-01-07 22:08 UTC, matze approved these changes

2025-01-11 21:38 UTC, merged